language: node_js
sudo: required
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
dist: trusty
script:
  - sudo $(which npm) test
# Send coverage data to Coveralls
after_script:
  - sudo $(which npm) run coverage
#  - npm run build -- --prod
#before_install:
#- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost